[package]
name = "check_bp768"
version = "0.1.0"
authors = ["Julius Hermelink <julius.hermelink@mpi-sp.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "check_bp768"
crate-type = ["cdylib"]

[dependencies]
rustfft = "5.0.1"
crossbeam = "0.8.0"
rand = "*"
rayon = "*"

[dependencies.pyo3]
version = "0.19.2"

[features]
kyber768 = []
extension-module = ["pyo3/extension-module", "kyber768"]
default = ["extension-module"]

[dependencies.belief_propagation]
git = "https://github.com/juliusjh/belief_propagation.git"
branch = "main"
features = ["info_output", "progress_output"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
